<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="instructions.css">  
</head>

<%@include file="header.jsp" %>
<body>
<div id="instructions">
<h2>Instructions to Solve Beam</h2>
    <ul>
        <li>Click Create/Update Diagram at any to see changes to diagram</li>
        <li>Click Add Forces to create input fields for forces</li>
        <li>Click Solve to calculate reactions</li>
        <li>Sign Conventions: Up is positive at 0 degrees. Clockwise is positive.</li>
    </ul>

<h2>Instructions to Solve Truss</h2>
    <ul>
        <h4>Diagram:</h4>
        <li>Click Create/Update Diagram at any to see changes to diagram</li>
        <li>Diagram scales based on overall size of members. All existing member fields must be filled in to see diagram</li>
        <li>Right is positive on x-axis. Up is positive on y-axis</li>
        <h4>Members:</h4>
        <li>Click Add Members to add structural members to the truss</li>
        <li>Members must intersect at endpoints</li>
        <li>To make 2 members intersect, break each lines into two smaller lines</li>
        <h4>Forces:</h4>
        <li>Sign Conventions: Up is positive at 0 degrees. Clockwise is positive.</li>
        <li>Click Add Forces to create input fields for forces</li>
        <li>Forces must be located at endpoints (joints) of members</li> 
        <h4>Supports:</h4>
        <li>Roller support fixes motion vertically
        <li>Pin support fixes motion both horizontally and vertically</li>
        <li>Supports must be located on endpoints (joints) of members</li>
        <li>Click Solve to calculate reactions</li>
        <h4>Results:</h4>
        <li>Member Results: Positive number indicates member is in tension. Negative number indicates compression </li>
        <li>Support Reactions: Up is positive, right is positive.
    </ul>

<h2>FAQ</h2>
    <ul>
        <h4>What does this software do?</h4>
        <li>The Beam portion allows you to create a simply supported beam, add loads
        and calculate the forces at each of the supports. The Truss potion allows you to create a truss,
        add loads, and calculate the internal force in each member and the force at each support.</li>
        <h4>How does the software work?</h4>
        <li>The calculations for the beam and truss were programmed entirely in Java. It works by generating
        a system of equations based on the user inputs. The beam is done by generating the 3 static equations
        equilibrium. The truss equations are generated by the method of joints. The software looks at each unique joint,
        then generates equations based on geometry of the members that make up the joint, supports at the joint,
        and forces at the joint. Once the software generates system of equations, it interfaces with an 
        Apache Commons Math API in order to solve the equations. The front end interface is done with JavaScript and JQuery.
        The diagram is generated with a JavaScript drawing Library called Konva.js and AJAX is used to make
        calls to the server while allowing the diagram to stay on screen.
        <h4>Why do supports and forces need to be places on the joints?</h4>
        <li>The analysis of a statically determinate truss requires loads to be placed at the joints.
        placing loads along the members are a different class of problem that cannot be solved by
        this software.</li>
        <h4>Why 1 roller and 1 pin support? Can't I use 2 pin supports?</h4>
        <li>Two pin supports over constrains the truss with redundant supports, and cannot be solved by only using
        Newton's equations of equilibrium. There ends up more variables than equations. Extra information about how the beam/truss deforms are needed
        to solve the equations.
        <h4>Where are the units?</h4>
        <li>A dimensional analysis of the beam and tuss shows that units of length do not matter
        as long as you use a consistent set of length units (you can't mix inches, feet, meters, etc). The
        same is true for forces, if all force inputs are in pounds the output will be in pounds. Another way 
        to think about it is that all inputs and outputs are units of length and units of force.</li>
        <h4>What about canteliever supports, horizontal roller supports, or roller supports at any angle?</h4>
        <li>Those may be added in future releases!</li>
    </ul>

<h2>Legal Stuff</h2>
    <ul>
        <h4>While I have thoroughly tested the software and believe it provides accurate calculations:</h4>
        <li>I cannot guarantee 100% reliable results.</li>
        <li>THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
        </li>
    </ul>

</div>
</body>
<footer>Last Updated 08-22-18</footer>